server:
  port: 8088

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 6000
  application:
    name: ms-weather-gateway-zuul-client
  thymeleaf:
   # prefix: classpath:/templates/
    check-template-location: true
    cache: false
    #suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka
      enabled: true
      register-with-eureka: true
      fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    hostname: ms-weather-gateway-zuul-client
    prefer-ip-address: true

ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 5000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 3000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则report.html]请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000 #断路器超时时间，默认1000ms

feign:
  hystrix:
    enabled: true