server:
  port: 8080

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 6000
  thymeleaf:
   # prefix: classpath:/templates/
    check-template-location: true
    cache: false
    #suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html