server:
  port: 8085

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 6000
  application:
    name: ms-weather-city
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka
      enabled: true
      register-with-eureka: true
      fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    hostname: ms-weather-city
    prefer-ip-address: true
